**Se importan las librerias**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Lectura y extraccion de datos del archivo**

In [22]:
#Extraemos los datos del .csv
data= pd.read_excel('Dallas.xlsx')
data

,last_scraped,source,description,neighborhood_overview,host_name,host_since,host_response_time,host_acceptance_rate,host_is_superhost,host_neighbourhood,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2024-11-18,city scrape,Close to downtown and Uptown. Fast and conven...,Enjoy the heart of Dallas right out your door ...,Sasha,2010-11-26,within an hour,1.00,f,Oak Lawn,...,4.85,4.92,4.75,4.77,f,1,1,0,0,0.33
1,2024-11-18,previous scrape,Additional discount for 2nd and 3rd month. Per...,"The address is 4340 Cedar Springs Road Dallas,...",Robert,2011-11-17,within an hour,0.46,f,Oak Lawn,...,4.91,4.96,4.89,4.93,f,1,1,0,0,0.40
2,2024-11-18,city scrape,***** Over 30% Discounts for stays over 30 day...,Located in Turtle Creek neighborhood steps fro...,Michelle,2012-11-19,within an hour,0.90,f,Oak Lawn,...,4.91,4.97,4.91,4.76,f,1,1,0,0,0.49
3,2024-11-18,city scrape,NaN,NaN,Rodney,2011-07-11,a few days or more,0.42,f,North Central Dallas,...,4.85,4.85,4.81,4.78,f,1,0,1,0,0.24
4,2024-11-18,city scrape,"Traveling nurses, SMU students welcome - 10% d...",Wonderful big trees and nice sidewalks through...,Judy,2012-12-27,within an hour,0.95,t,Old Lake Highlands,...,4.93,4.93,4.92,4.83,f,3,0,3,0,0.72
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5302,2024-11-18,city scrape,"As you step inside, you are greeted by an open...",NaN,Abby,2020-10-25,within an hour,0.97,t,Dallas Downtown Historic District,...,NaN,NaN,NaN,NaN,t,2,2,0,0,NaN
5303,2024-11-18,city scrape,"After a day of adventure, relax in the cozy li...",Nearby attractions<br />Dallas Museum of Art -...,Ibrar,2019-09-22,within an hour,0.99,t,Glenbrook-Belltown,...,NaN,NaN,NaN,NaN,t,12,12,0,0,NaN
5304,2024-11-18,city scrape,Located five minutes from the Dallas Arboretum...,NaN,Isaac,2019-10-15,NaN,NaN,f,Casa View,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
5305,2024-11-18,city scrape,NaN,NaN,Leah,2024-08-27,NaN,NaN,f,Oak Cliff,...,NaN,NaN,NaN,NaN,f,1,1,0,0,NaN
5306,2024-11-18,city scrape,Newly constructed modern apartment right in th...,This property is right across the street from ...,Annie,2020-10-20,within an hour,0.94,f,North Arlington,...,NaN,NaN,NaN,NaN,f,7,7,0,0,NaN

**Identificacion de valores nulos**

In [23]:
data1= pd.read_excel('Dallas.xlsx')

In [24]:
#identificar valores nulos por columna 
valores_nulos= data1.isnull().sum()
valores_nulos

last_scraped                                       0
source                                             0
description                                       37
neighborhood_overview                           2748
host_name                                          0
host_since                                         0
host_response_time                               386
host_acceptance_rate                             273
host_is_superhost                                233
host_neighbourhood                               435
host_total_listings_count                          0
host_verifications                                 0
host_has_profile_pic                               0
host_identity_verified                             0
neighbourhood_cleansed                             0
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms_text                                     2
bedrooms                                          47
beds                                             258
amenities                                          0
price                                            272
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                  29
calendar_last_scraped                              0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
review_scores_rating                             780
review_scores_cleanliness                        780
review_scores_checkin                            780
review_scores_communication                      780
review_scores_location                           780
review_scores_value                              780
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                                780
dtype: int64

In [25]:
#identificar valores nulos por dataframe 
valores_nulos=data1.isnull().sum().sum()
valores_nulos

np.int64(10180)

**Metodos de sustitucion de valores nulos**

In [26]:
#Realizamos una copia del dataframe 
data2=data1.copy()

In [27]:
#Sustitucion de valores nulos por un valor de texto dado que no proporcionan una descripcion, llenarlo con una descripcion diciendo que no esta disponible sirve para no dejar los valores nulos.
data2["description"]=data2["description"].fillna("No description available")

In [28]:
#Sustitucion de valores nulos por un valor de texto, al igual que la columna anterior, las usamos para dar entender que la informacion no fue proporciona y va acorde con el tipo de valor que tiene la columna.
data2["neighborhood_overview"]=data2["neighborhood_overview"].fillna("No overview available")

In [29]:
#Sustitucion de valores nulos por un valor de texto, al igual que la columna anterior optamos por sustituir el valor nulo por desconocido, en las columnashost_response_time" y "host_neighbourhood.
data2[["host_response_time", "host_neighbourhood"]]=data2[["host_response_time", "host_neighbourhood"]].fillna("Unknown")

In [30]:
#Sustituir valores nulos con promedio o media, se eligio este metodo para estas columnas porque son numéricas, y la media es adecuada para representar valores faltantes sin distorsionar el análisis.
data2[["host_acceptance_rate", "review_scores_rating", "review_scores_cleanliness", "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value"]]=data2[["host_acceptance_rate", "review_scores_rating", "review_scores_cleanliness", "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value"]].fillna(round(data1[["host_acceptance_rate", "review_scores_rating", "review_scores_cleanliness", "review_scores_checkin", "review_scores_communication", "review_scores_location", "review_scores_value"]].mean(),1))

In [31]:
#Sustitucion de valores nulos por un valor en concreto, al igual que el anterior este lo elegimos dado que si no posee un valor es razonable suponer no tiene el dato y el 0 sirve como indicador de datos desconocidos.
data2[["host_is_superhost", "has_availability", "reviews_per_month"]]=data2[["host_is_superhost", "has_availability", "reviews_per_month"]].fillna(0)

In [32]:
#Sustitucion de valores nulos por valores no nulos hacia adelante, ocupamos este metodo ya que visualizando los valores, nos dimos cuenta que el valor adelante de el suele ser el mismo o similar al de la columna y queda perfecto como sustitucion de los valores nulos 
data2["bathrooms_text"]=data2["bathrooms_text"].fillna(method="ffill")

C:\Users\leirb\AppData\Local\Temp\ipykernel_24936\361353304.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data2["bathrooms_text"]=data2["bathrooms_text"].fillna(method="ffill")

In [33]:
#Sustitucion por mediana, se opto por este metodo dado que la mediana es más robusta frente a valores atípicos, especialmente útil en datos como precios y cantidades.
data2[["bedrooms", "beds", "price"]]=data2[["bedrooms", "beds", "price"]].fillna(round(data1[["bedrooms", "beds", "price"]].median(),1))

**Se revisa que ya no existan valores nulos**

In [34]:
#Identificar valores nulos por columna
valores_nulos=data2.isnull().sum()
valores_nulos

last_scraped                                    0
source                                          0
description                                     0
neighborhood_overview                           0
host_name                                       0
host_since                                      0
host_response_time                              0
host_acceptance_rate                            0
host_is_superhost                               0
host_neighbourhood                              0
host_total_listings_count                       0
host_verifications                              0
host_has_profile_pic                            0
host_identity_verified                          0
neighbourhood_cleansed                          0
latitude                                        0
longitude                                       0
property_type                                   0
room_type                                       0
accommodates                                    0
bathrooms_text                                  0
bedrooms                                        0
beds                                            0
amenities                                       0
price                                           0
minimum_nights                                  0
maximum_nights                                  0
minimum_minimum_nights                          0
maximum_minimum_nights                          0
minimum_maximum_nights                          0
maximum_maximum_nights                          0
minimum_nights_avg_ntm                          0
maximum_nights_avg_ntm                          0
has_availability                                0
calendar_last_scraped                           0
number_of_reviews                               0
number_of_reviews_ltm                           0
number_of_reviews_l30d                          0
review_scores_rating                            0
review_scores_cleanliness                       0
review_scores_checkin                           0
review_scores_communication                     0
review_scores_location                          0
review_scores_value                             0
instant_bookable                                0
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
dtype: int64

In [35]:
valores_nulos=data2.isnull().sum().sum()
valores_nulos

np.int64(0)

**Se crea el archivo .csv sin existencia de valores nulos**

In [36]:
#Convertir DataFrame a csv
data2.to_csv('Datos_de_DallasTexas_sin_nulos.csv')